### ISSUE TITLE
Opening Debugger with GPGX loaded throws exception, crashing Mono

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#2769]
"Got a SIGSEGV while executing native code."

Repro'd at 4d91b59ca i.e. after #2766 was fixed.

**Comment by YoshiRulz** [comment]
Also crashes on Windows, I used 2.6.3 dev at f1da6e6cd.
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BizHawk.Client.EmuHawk.GenericDebugger.get_PCRegister()
   at BizHawk.Client.EmuHawk.GenericDebugger.get_CanDisassemble()
   at BizHawk.Client.EmuHawk.GenericDebugger.EngageDebugger()
   at BizHawk.Client.EmuHawk.GenericDebugger.Restart()
   at BizHawk.Client.EmuHawk.ToolManager.Load[T](Boolean focus, String toolPath)
   at BizHawk.Client.EmuHawk.MainForm.DebuggerMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by YoshiRulz** [comment]
Yes, this was fixed by https://github.com/TASEmulators/BizHawk/commit/59d76294c9f92aab97ea4fb46d011a31e1f4a731.
