### ISSUE TITLE
Segfault on debugger execution breakpoint with GPGX core

### ISSUE THREAD

**Issue by flamewing** [TASEmulators/BizHawk#2818]
### Summary
On Windows 10 (both with official release and latest developer build), with Genesis Plus GX core, setting an execute breakpoint on the debugger causes BizHawk to crash when the code in question is executed.

![image](https://user-images.githubusercontent.com/6319024/123168343-22cdaa80-d478-11eb-9a61-8a4a81abc3d0.png)

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. load a Genesis ROM
2. open the debugger
3. set a breakpoint on execute
4. when the breakpoint executes, BizHawk crashes with a segfault

### Output
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond)
   at System.TimeZoneInfo.TransitionTimeToDateTime(Int32 year, TransitionTime transitionTime)
   at System.TimeZoneInfo.GetDaylightTime(Int32 year, AdjustmentRule rule)
   at System.TimeZoneInfo.GetIsDaylightSavingsFromUtc(DateTime time, Int32 Year, TimeSpan utc, AdjustmentRule rule, Boolean& isAmbiguousLocalDst, TimeZoneInfo zone)
   at System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc(DateTime time, Boolean& isAmbiguousLocalDst)
   at System.DateTime.get_Now()
   at System.Collections.Generic.List`1.Add(T item)
   at BizHawk.Emulation.Common.MemoryCallbackSystem.Call(ObservableCollection`1 cbs, UInt32 addr, UInt32 value, UInt32 flags, String scope)
   at BizHawk.Emulation.Common.MemoryCallbackSystem.CallMemoryCallbacks(UInt32 addr, UInt32 value, UInt32 flags, String scope)
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.<InitMemCallbacks>b__51_0(UInt32 a)
   at Bizhawk.BizInvokeProxyLibGPGX.gpgx_advance()
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.FrameAdvance(IController controller, Boolean render, Boolean renderSound)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
   at BizHawk.Client.EmuHawk.Program.Main(String[] args)
Segmentation fault
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.6.2; Win10 Home; Intel/NVIDIA
- [BizHawk developer build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts) build at 28ff96deb5; Win10 Home; Intel/NVIDIA

**Comment by getCursorsExe** [comment]
This crash code is similar to #2794

**Comment by CasualPokePlayer** [comment]
How does that say anything? All that means in both cases some memory was read/written that was not supposed to be read/written. That's fairly generic and does not mean any sort of correlation.

**Comment by flamewing** [comment]
For what is worth, the segfault happens on read/write breakpoint types as well.

**Comment by vadosnaprimer** [comment]
Memory hooks don't work with the current iteration of waterbox setup.
https://github.com/TASVideos/BizHawk/issues/2585

**Comment by CasualPokePlayer** [comment]
Fixed in https://github.com/TASEmulators/BizHawk/commit/2ea62ffea628080cfc1d1f3fbb904e3238b5a491
