### ISSUE TITLE
Cannot open imported .vbm movies with TAStudio

### ISSUE THREAD

**Issue by despoa** [TASEmulators/BizHawk#3156]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
By opening an .bk2 file converted from a .vbm file for a Game Boy game, TAStudio will crash and BizHawk won't be able to open any games until it's restarted.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Import a .vbm movie made for a GB/C game, creating a .bk2 file.
2. Open the GB/C game the .vbm movie was made for.
3. Open the resulting .bk2 file in TAStudio.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.MovieConversionExtensions.ToTasMovie(IMovie old)
   at BizHawk.Client.Common.MovieSession.ConvertToTasProj()
   at BizHawk.Client.EmuHawk.TAStudio.ConvertCurrentMovieToTasproj()
   at BizHawk.Client.EmuHawk.TAStudio.LoadMovieFile(String filename, Boolean askToSave)
   at BizHawk.Client.EmuHawk.TAStudio.OpenTasMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.7; Win10 Home 19044; Intel/Nvidia

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
VBM import was recently refactored, try 2.8rc1

**Comment by despoa** [comment]
Works in 2.8rc1.
