### ISSUE TITLE
SNES Graphics Debugger Exception when trying to freeze tile

### ISSUE THREAD

**Issue by Masterjun3** [TASEmulators/BizHawk#3195]
### Summary
In the SNES Graphics Debugger you have the ability to freeze a tile or item to the left info window by rightclicking. However when trying it an exception window appears. You can click Continue and the tool and emulator recover neatly and it's possible to continue using it. It's just that the freeze doesn't work.
It seems like the last BizHawk version where the feature worked was 1.4.2 from two years ago.

### Repro
1. Open SNES ROM in BSNES core.
2. Open Graphics Debugger.
3. Rightclick in the main window to freeze a tile to the left info window.
4. Exception occurs.

### Output
```
System.ArgumentException: Property set method not found.
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at BizHawk.Client.EmuHawk.ControlExtensions.Clone[T](T controlToClone)
   at BizHawk.Client.EmuHawk.SNESGraphicsDebugger.Freeze()
   at BizHawk.Client.EmuHawk.SNESGraphicsDebugger.viewer_MouseDown(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Host env.
- BizHawk 2.8; Win10

**Comment by YoshiRulz** [comment]
Is that `Clone` ever passed a `Label`? If so, it would be better to do `typeof(Control).GetProperty("AutoSize")?.SetValue(instance, false, null);` (see doc comment) to restore the old behaviour.

**Comment by Morilli** [comment]
What old behavior? As far as I can see, there are only `CheckBox`, `TextBox`, `LocLabelEx` and `SNESGraphicsViewer` passed.

**Comment by YoshiRulz** [comment]
Old behaviour being it sets `AutoSize` by reflection on `Label`s. It doesn't really matter so long as that callsite works, because it's the only callsite.
