### ISSUE TITLE
EmuHawk on Win10 produces "Illegal characters in path" error when opening a recent ROM via Windows's "Recent" menu

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3224]
![image](https://user-images.githubusercontent.com/83939/164650301-5b7c2179-0304-422a-9548-7cb24432da23.png)
![image](https://user-images.githubusercontent.com/83939/164650800-d97ea68d-81ba-48df-a257-c26ae1a1519d.png)
Whenever I try to open the following ROM path `B:\ROMs\B3313 v0.7 by Christopher Rios Lillo.z64` using Windows 10's "Recent" menu, in either the Start menu or by right-clicking it on the Taskbar, the following error occurs:
```
System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at BizHawk.Common.PathExtensions.PathExtensions.MakeAbsolute(String path, String cwd)
   at BizHawk.Client.EmuHawk.MainForm..ctor(ParsedCLIFlags cliFlags, IGL gl, Func`1 getConfigPath, Func`1 getGlobalConfig, Action`1 updateGlobalSound, String[] args, IMovieSession& movieSession, Boolean& exitEarly)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```
This error does NOT occur if opening it using the **internal** Recent ROM menu inside EmuHawk.

**Comment by YoshiRulz** [comment]
Interesting. Stacktrace suggests it's a filesystem issue.

Which version are you using?

**Comment by webbedspace** [comment]
This is EmuHawk 2.8 on Windows 10 Pro 19044

**Comment by Meerkov** [comment]
Didn't this happen with the Lua system too? It's probably because it's taking an Absolute path here, and trying to append it to the Working Directory.

(Completely blind guess, but it sounds right to me).

**Comment by YoshiRulz** [comment]
It's writing e.g. `.\EmuHawk.exe "*OpenRom*C:\path\to.rom"` but only expecting `C:\path\to.rom`.

**Comment by kalimag** [comment]
This still happens with roms inside archives, due to the pipe in the path:

```
System.ArgumentException: Illegal characters in path.
   bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   bei System.IO.Path.GetRootLength(String path)
   bei System.IO.Path.GetPathRoot(String path)
   bei BizHawk.Common.PathExtensions.PathExtensions.IsAbsolute(String path) in /src/BizHawk.Common/Extensions/PathExtensions.cs:Zeile 54.
   bei BizHawk.Common.PathExtensions.PathExtensions.MakeAbsolute(String path, String cwd) in /src/BizHawk.Common/Extensions/PathExtensions.cs:Zeile 109.
   bei BizHawk.Client.EmuHawk.MainForm..ctor(ParsedCLIFlags cliFlags, IGL gl, Func`1 getConfigPath, Func`1 getGlobalConfig, Action`1 updateGlobalSound, String[] args, IMovieSession& movieSession, Boolean& exitEarly) in /src/BizHawk.Client.EmuHawk/MainForm.cs:Zeile 695.
   bei BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in /src/BizHawk.Client.EmuHawk/Program.cs:Zeile 348.
```
