### ISSUE TITLE
mGBA event.onmemoryread only calls the latest callback.

### ISSUE THREAD

**Issue by besteon** [TASEmulators/BizHawk#3230]
My script looks something like this:
```
    event.onmemoryread(Program.HandleTrainerSentOutPkmn, GameSettings.TrainerSentOutPkmn, "HandleTrainerSentOutPkmn")
        event.onmemoryread(Program.HandleWeHopeToSeeYouAgain, GameSettings.WeHopeToSeeYouAgain, "HandleWeHopeToSeeYouAgain")
```
When EITHER of these memory addresses are read, only the latest callback is executed. In this example, its `Program.HandleWeHopeToSeeYouAgain`

Some pseudocode:
```
function callbackA()
    print("callbackA")
end

function callbackB()
    print("callbackB")
end

event.onmemoryread(callbackA, 0xdeadbeef)
event.onmemoryread(callbackB, 0xbeefdead)
```

When 0xdeadbeef OR 0xbeefdead is read and triggers the callback, the result will be "callbackB", even if 0xdeadbeef was the read address. I hope that makes sense.

Env:
Bizhawk 2.8 and https://github.com/TASEmulators/BizHawk/commit/14984aea2d8530a259e92d65eb8b25663eb723d8
Windows 10
mGBA Core

**Comment by besteon** [comment]
```
System.NotImplementedException: Executes can not be used from watch points.
   at BizHawk.Emulation.Cores.Nintendo.GBA.CallbackContainer.get_WatchPointType() in C:\Users\PaulH\Documents\Projects\emulation\BizHawk\src\BizHawk.Emulation.Cores\Consoles\Nintendo\GBA\MGBAMemoryCallbackSystem.cs:line 204
   at BizHawk.Emulation.Cores.Nintendo.GBA.MGBAMemoryCallbackSystem.RunReadWriteCallback(UInt32 addr, mWatchpointType type, UInt32 oldValue, UInt32 newValue) in C:\Users\PaulH\Documents\Projects\emulation\BizHawk\src\BizHawk.Emulation.Cores\Consoles\Nintendo\GBA\MGBAMemoryCallbackSystem.cs:line 149
   at BizHawk.Emulation.Cores.Nintendo.GBA.MGBAHawk.FrameAdvance(IController controller, Boolean render, Boolean renderSound) in C:\Users\PaulH\Documents\Projects\emulation\BizHawk\src\BizHawk.Emulation.Cores\Consoles\Nintendo\GBA\MGBAHawk.cs:line 126
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```
This occurred when the event.onmemoryread address was read

**Comment by YoshiRulz** [comment]
Should be fixed as of https://github.com/TASEmulators/BizHawk/commit/cd8f5b420339ab589d0f7908c0232a907609d384.
