### ISSUE TITLE
GenPlus-GX savestates saved in 2.7 don't work in 2.8.

### ISSUE THREAD

**Issue by webbedspace** [TASEmulators/BizHawk#3231]
### Repro
Here's a zip containing all of the save states and the ROM in question: [GEN.zip](https://github.com/TASEmulators/BizHawk/files/8596515/GEN.zip) These load in 2.7 but cause the following error in 2.8:

```
System.InvalidOperationException: Waterbox Error: Bad hash for state
   at BizHawk.Emulation.Cores.Waterbox.WaterboxHostNative.ReturnData.GetDataOrThrow()
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.LoadStateBinary(BinaryReader reader)
   at BizHawk.Client.Common.ZipStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback)
   at BizHawk.Client.Common.ZipStateLoader.GetCoreState(Action`1 callbackBinary, Action`1 callbackText)
   at BizHawk.Client.Common.SavestateFile.Load(String path)
   at BizHawk.Client.EmuHawk.MainForm.LoadState(String path, String userFriendlyStateName, Boolean suppressOSD)
   at BizHawk.Client.EmuHawk.MainForm.LoadQuickSave(String quickSlotName, Boolean suppressOSD)
   at BizHawk.Client.EmuHawk.MainForm.CheckHotkey(String trigger)
   at BizHawk.Client.EmuHawk.MainForm.<ProcessInput>b__129_1(Boolean current, String trigger)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at BizHawk.Client.EmuHawk.MainForm.ProcessInput(InputCoalescer hotkeyCoalescer, ControllerInputCoalescer finalHostController, Func`2 searchHotkeyBindings, Func`2 activeControllerHasBinding)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

I looked at the release notes for 2.8 but savestate incompatibility wasn't listed among them. If this can't be fixed then I'll understand.

### Host env.
- BizHawk 2.7 and 2.8; Windows 10 AMD

**Comment by CasualPokePlayer** [comment]
The core was changed in 2.8 https://github.com/TASEmulators/BizHawk/commit/05f11be191d857214499d2de5188da58e9187387

Any core modification invalidates previous savestates.

**Comment by webbedspace** [comment]
Thanks for the quick reply. Still, it'd be nice if guaranteed save state incompatibilities like this were listed in the release notes next time, especially since it's not well-documented which cores are Waterbox and which aren't.

**Comment by getCursorsExe** [comment]
Maybe someone should add a savestate converter?

**Comment by webbedspace** [comment]
> Maybe someone should add a savestate converter?

Nice thought, but it ain't gonna happen.

**Comment by CasualPokePlayer** [comment]
> Maybe someone should add a savestate converter?

That is impossible for waterbox cores.

**Comment by getCursorsExe** [comment]
Or perhaps this has to do with the savestate format?

**Comment by CasualPokePlayer** [comment]
Waterbox core savestates are raw dumps of core memory, including every from internal state and pointers. How memory is laid out changes with every core update, and you have no idea what's a pointer (which would need to be changed) in this dump, not to mention anything else.

**Comment by CasualPokePlayer** [comment]
More proper warning message was implemented in https://github.com/TASEmulators/BizHawk/commit/ee241dc6263e4261216c454b4a3410850e7530bd

**Comment by getCursorsExe** [comment]
Fixing this would requrie completely rewriting the waterbox, which is not what you want to do.

**Comment by Godivctor** [comment]
fuck
