### ISSUE TITLE
[TAStudio] Switching consoles throws input display exception

### ISSUE THREAD

**Issue by kalimag** [TASEmulators/BizHawk#3417]
### Summary
TAStudio causes an exception when input display is enabled and two different consoles (or rather, cores with different inputs?) are used consecutively.

Debugger reveals that `Bk2ControllerDefinition.OrderedControlsFlat` still contains the previous system's controls while `Bk2ControllerDefinition.BoolButtons` contains the current system's controls. 

### Repro
1. Start BizHawk
2. Enable input display
3. Load NES ROM (for example)
4. Play movie OR open TAStudio
5. (Optionally) Stop movie OR close TAStudio
6. Load Genesis ROM (for example)
7. Open TAStudio
8. Unpause emulation
9. Enable recording mode
10. Exception occurs

### Output

```
System.Exception: OrderedControlsFlat/ControlsOrdered contains an input name which is neither a button nor an axis

   at BizHawk.Client.Common.Bk2InputDisplayGenerator.<>c__DisplayClass2_0.<.ctor>b__0(String button) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\display\IInputDisplayGenerator.cs:line 28
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BizHawk.Client.Common.Bk2InputDisplayGenerator..ctor(String systemId, IController source) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\display\IInputDisplayGenerator.cs:line 23
   at BizHawk.Client.Common.OSDManager.MakeStringFor(IController controller, Boolean cache) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DisplayManager\OSDManager.cs:line 218
   at BizHawk.Client.Common.OSDManager.InputPrevious() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DisplayManager\OSDManager.cs:line 201
   at BizHawk.Client.Common.OSDManager.DrawScreenInfo(IBlitter g) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DisplayManager\OSDManager.cs:line 295
   at BizHawk.Client.Common.DisplayManagerBase.<>c__DisplayClass43_0.<BuildDefaultChain>b__0() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DisplayManager\DisplayManagerBase.cs:line 295
   at BizHawk.Client.Common.Filters.OSD.Run() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DisplayManager\Filters\Gui.cs:line 730
   at BizHawk.Client.Common.DisplayManagerBase.RunFilterChainSteps(Int32& rtCounter, RenderTarget& rtCurr, Boolean& inFinalTarget) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DisplayManager\DisplayManagerBase.cs:line 973
   at BizHawk.Client.EmuHawk.DisplayManager.UpdateSourceDrawingWork(JobInfo job) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\DisplayManager\DisplayManager.cs:line 108
   at BizHawk.Client.Common.DisplayManagerBase.UpdateSourceInternal(JobInfo job) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DisplayManager\DisplayManagerBase.cs:line 921
   at BizHawk.Client.Common.DisplayManagerBase.UpdateSource(IVideoProvider videoProvider) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DisplayManager\DisplayManagerBase.cs:line 491
   at BizHawk.Client.EmuHawk.MainForm.Render() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 2376
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 787
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\Program.cs:line 273
   at BizHawk.Client.EmuHawk.Program.Main(String[] args) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\Program.cs:line 90
```

### Host env.
- BizHawk 2.9 (debug build f291132) on Windows 10
- BizHawk 2.8 on Windows 10

**Comment by YoshiRulz** [comment]
Does this affect 2.7? If not I suspect https://github.com/TASEmulators/BizHawk/commit/8b1a1393a93cef69ac1732c8fc5be69c033df1c8.

**Comment by kalimag** [comment]
In 2.7, these steps cause no exception related to input display.

However, the same repro steps also cause TAStudio input recording to break, where some inputs are recorded as different inputs, and others are not recorded at all. This happens on at least 2.7, 2.8 and 2.9

**Comment by kalimag** [comment]
After some more testing, it seems that the input display related crash started in 2.8

The input recording issue started in 2.6.2

I would suspect that they have the same underlying cause, but I don't know that for sure.

**Comment by YoshiRulz** [comment]
Due to the way [this assertion](https://github.com/TASEmulators/BizHawk/blob/f29113287e88c6a644dbff30f92a9833307aad20/src/BizHawk.Client.Common/display/IInputDisplayGenerator.cs#L22-L28) is coded, if the first core's controls are a subset of the second core's, it will succeed despite ostensibly having mismatched definitions. So NES => SNES will not crash, but SNES => NES will.

---

Point re: `OrderedControlsFlat` is correct. It's generated from `Bk2ControllerDefinition.ControlsFromLog`, which is generated from the `key` ctor parameter, with the argument being `Bk2Movie.LogKey` here:
https://github.com/TASEmulators/BizHawk/blob/f29113287e88c6a644dbff30f92a9833307aad20/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs#L144
The `LogKey` is confusingly read from the input log in `default.tasproj`, the file that's created, written to disk, and immediately loaded during TAStudio startup. When writing the input log, the `MovieController` is used to generate that line:
https://github.com/TASEmulators/BizHawk/blob/f29113287e88c6a644dbff30f92a9833307aad20/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.InputLog.cs#L15-L19
But `MovieController` was never updated! It's still the old core's controls.
Usually when loading a movie, `MainForm` will call `MovieSession.RunQueuedMovie` to set it, but TAStudio bypasses that.

---

So my fix is for `TAStudio.StartNewTasMovie` to mimic `MainForm.StartNewMovie`. #3418
But it could be that `LogKey` is supposed to be set at the point of writing `default.tasproj` to disk, which would make the condition linked above fail and use the provided `LogKey` instead. This interacts with #3274/#2567 in ways I don't full understand.

**Comment by Morilli** [comment]
I can't reproduce this issue since 683aa263a0ccdc8a4747fbb4ef359842b52c9a26, did that commit fix this or is there still broken behavior?

**Comment by YoshiRulz** [comment]
That commit mitigated the exception in OP, but the `LogKey` is still wrong.

---

I wasn't able to reproduce the bug described in https://github.com/TASEmulators/BizHawk/issues/3417#issuecomment-1282690592 where inputs one one column would actually press a different button. I made this change to QuickNes, then did the same repro, opening TAStudio on NesHawk first. Start was still Start, etc.
```csharp
private class HackedControllerDefinition : ControllerDefinition
{
	public HackedControllerDefinition(string name) : base(name) {}
	protected override IReadOnlyList<IReadOnlyList<string>> GenOrderedControls()
	{
		var players = base.GenOrderedControls().ToList();
		players.Add(players[1].Order().ToList()); // UDLRSsBA => ABDLRsSU
		players.RemoveAt(1);
		return players;
	}
}
// then change type at top of SetControllerDefinition
```

**Comment by kalimag** [comment]
> I wasn't able to reproduce the bug described in [#3417 (comment)](https://github.com/TASEmulators/BizHawk/issues/3417#issuecomment-1282690592) where inputs one one column would actually press a different button.

The issue was with the recording mode, not manual input editing.

On 2.6.2, after switching from NES to Genesis, pressing A on the controller acts as A in the game and is displayed as A in the input display, but is recorded in the Start column in TAStudio. Replaying the recorded section in TAStudio then presses Start in the game.

But I can't reproduce this on 9393e1b76 anymore, so this seems have been fixed along the way.
