### ISSUE TITLE
Loading GBA homebrew causes access violation

### ISSUE THREAD

**Issue by kalimag** [TASEmulators/BizHawk#3421]
### Summary
Loading the ROM found at https://github.com/heroldev/AGB-buttontest causes BizHawk to crash because of an access violation while creating the core.

Since it's a homebrew it's entirely possible that there's something wrong with the ROM, but in any case it probably shouldn't cause memory violations.

### Repro
1. Run affected BizHawk version
2. Load specified ROM
3. Hard crash occurs immediately

### Output
```
System.Reflection.TargetInvocationException:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at BizHawk.Emulation.Cores.CoreInventory.Core.CreateUsingLegacyConstructorParameters(ICoreInventoryParameters cip) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Emulation.Cores\CoreInventory.cs:line 125
   at BizHawk.Emulation.Cores.CoreInventory.Core.Create(ICoreInventoryParameters cip) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Emulation.Cores\CoreInventory.cs:line 135
   at BizHawk.Client.Common.RomLoader.MakeCoreFromCoreInventory(CoreInventoryParameters cip, String forcedCoreName) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\RomLoader.cs:line 403
   at BizHawk.Client.Common.RomLoader.LoadOther(CoreComm nextComm, HawkFile file, String forcedCoreName, IEmulator& nextEmulator, RomGame& rom, GameInfo& game, Boolean& cancel) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\RomLoader.cs:line 505
   at BizHawk.Client.Common.RomLoader.LoadRom(String path, CoreComm nextComm, String launchLibretroCore, String forcedCoreName, Int32 recursiveCount) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\RomLoader.cs:line 708
   at BizHawk.Client.EmuHawk.MainForm.LoadRomInternal(String path, LoadRomArgs args, Boolean& failureIsFromAskSave) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 3802
   at BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args, Boolean& failureIsFromAskSave) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 3700
   at BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 3696
   at BizHawk.Client.EmuHawk.MainForm.LoadRom(String filename, String archive) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.FileLoader.cs:line 117
   at BizHawk.Client.EmuHawk.MainForm.FormDragDrop_internal() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.FileLoader.cs:line 276
   at BizHawk.Client.EmuHawk.MainForm.<CheckMessages>b__228_0() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 2290
   at BizHawk.Client.Common.DialogControllerExtensions.DoWithTempMute(IDialogController dialogController, Action action) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.Common\DialogControllerExtensions.cs:line 12
   at BizHawk.Client.EmuHawk.MainForm.CheckMessages() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 2286
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 789
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\Program.cs:line 273
   at BizHawk.Client.EmuHawk.Program.Main(String[] args) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Client.EmuHawk\Program.cs:line 90
```

```
AccessViolationException: 
   at BizHawk.Emulation.Cores.Nintendo.GBA.MGBAHawk..ctor(Byte[] file, CoreComm comm, SyncSettings syncSettings, Settings settings, Boolean deterministic, GameInfo game) in H:\Projekte\Visual Studio\bizhawk\src\BizHawk.Emulation.Cores\Consoles\Nintendo\GBA\MGBAHawk.cs:line 53
```

### Host env.
- BizHawk dev builds from a1e9790a39422998dea26588bf19beace2c8b70a onwards; Win10 Pro 21H1; Intel/NVIDIA
- Does not occur on BizHawk 2.8 or dev builds before a1e9790a39422998dea26588bf19beace2c8b70a
- Does not occur on standalone mGBA 0.9.3 x64, mGBA 0.10.0 x64, mGBA dev build 7757-75da9f0a9 x64

**Comment by CasualPokePlayer** [comment]
Seems to be crashing on this line
https://github.com/TASEmulators/mgba/blob/3ea887153d33ca719195b85e2a781987f835ec14/src/platform/bizhawk/bizinterface.c#L291
cart is a NULL pointer here according to gdb, so I guess the core rejected the ROM in loadROM?

**Comment by CasualPokePlayer** [comment]
Seems the ROM is not actually rejected per se, but it is detected as a multiboot ROM (which is only loaded in RAM, so there is no ROM space allocated). This detection does seem valid anyways looking at that ROM's source.
