### ISSUE TITLE
Recording a movie for Atari 2600 Q-bert crashes Mame

### ISSUE THREAD

**Issue by adelikat** [TASEmulators/BizHawk#3448]
Opening Q-bert (1988) (Atari) [!].a26 loads with ATari2600Hawk successfully.  When attempting to record a movie, it  causes Mame to crash in RomLoader, not sure why mame got involved

Crash report dialog contents:
```
************** Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at BizHawk.Emulation.Cores.Arcades.MAME.MAMEMachineDB.IsMAMEMachine(String path) in C:\Repos\BizHawk\src\BizHawk.Emulation.Cores\Arcades\MAME\MAMEMachineDB.cs:line 56
   at BizHawk.Client.Common.RomLoader.LoadRom(String path, CoreComm nextComm, String launchLibretroCore, String forcedCoreName, Int32 recursiveCount) in C:\Repos\BizHawk\src\BizHawk.Client.Common\RomLoader.cs:line 598
   at BizHawk.Client.EmuHawk.MainForm.LoadRomInternal(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   at BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args, Boolean& failureIsFromAskSave)
   at BizHawk.Client.EmuHawk.MainForm.RebootCore()
   at BizHawk.Client.EmuHawk.MainForm.StartNewMovie(IMovie movie, Boolean record)
   at BizHawk.Client.EmuHawk.RecordMovie.Ok_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by CasualPokePlayer** [comment]
A look at the stack trace says MAME isn't crashing per se, but the MAME zip detection is crashing (due to the path given being invalid???)

**Comment by CasualPokePlayer** [comment]
The illegal character here is the | for an already binded archive entry. The saved rom args (used for reboot core) would have <archive path>|<file in archive> for the path.

This issue as a note will not occur if the rom file is opened directly, only when an archive file with the rom file is opened (and anything rebooting the core will trigger it). So opening `Q-bert (1988) (Atari) [!].a26` will not crash, but opening `Q-bert (1988) (Atari) [!].zip` will.
