### ISSUE TITLE
Custom Shader (*.CG) support latest builds !

### ISSUE THREAD

**Issue by metagondria** [TASEmulators/BizHawk#3495]
Hello,

I have found one of if not the best .CG shader to polish native psx graphics.  
But the problem is that it only works up untill build 2.4.2 (x64) !!  

In later builds, bizhawk throws an error and emediatly closes !!

I would be happy if i could continue and keep using this shader in latest build.
The shader is called "4xbr-hybrid-crt.cgp" .  

Again the shader works flawless in builds up to 2.4.2..  

I just have tried out the Release candidate 2.9.x, and i get the "unhandled exception" error when i try to use and select custom shader folder btw !!

If you want to get the physical file itself, let me know.  ill post it asap.

Thanks in advance,

**Comment by CasualPokePlayer** [comment]
Please post the problematic shader file.

**Comment by metagondria** [comment]
> Please post the problematic shader file.

Sure, see below for shader package.
Be sure to choose the hybrid-crt one.

[shaders.zip](https://github.com/TASEmulators/BizHawk/files/10252424/shaders.zip)

Must say, one of the most gorgeous shaders that exist atm (noticeable psx graphics improvement) :)
It would be an shame if that shader couldn't be used anymore !!

cheers,

**Comment by CasualPokePlayer** [comment]
https://github.com/TASEmulators/BizHawk/commit/8d5f7b547864514e0ebb247aa6099298e64edc60 probably fixes it.

**Comment by metagondria** [comment]
> 
fixed ? 
Whats the next step for me to do now presumable ? Sorry no expert here, just end user .

**Comment by CasualPokePlayer** [comment]
For now, nothing, until a new CI build kicks in (builds are limited due to restraints with the CI we have).

**Comment by YoshiRulz** [comment]
re: https://github.com/TASEmulators/BizHawk/commit/8d5f7b547864514e0ebb247aa6099298e64edc60, That's weird, because before https://github.com/TASEmulators/BizHawk/commit/f1f0f1695c3dbd18ff939d06a8f718733ee2a957 the `OpenFileDialog` in question wasn't given an init dir, so it should have defaulted to `string.Empty`. Unless the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog.initialdirectory?view=netframework-4.8#property-value) are lying again...

**Comment by CasualPokePlayer** [comment]
Path.GetDirectoryName is what threw, not OpenFileDialog.

**Comment by YoshiRulz** [comment]
@metagondria Please try [this dev build](https://gitlab.com/TASVideos/BizHawk/-/jobs/3499656798/artifacts/download?file_type=archive).

**Comment by metagondria** [comment]
> @metagondria Please try [this dev build](https://gitlab.com/TASVideos/BizHawk/-/jobs/3499656798/artifacts/download?file_type=archive).

Thanks for the support..

But instead i get the following ↓ error now, when loading the CG shader in question !!

Anyway, thanks for trying..  

But currently i have switched over to RetroARch / Beetle (psx) emu, and converted the saveram savefiles in order for me to continue the games . 
 
Thanks to an member over there, he shared an .Slang (Vulkan) variant shader to load in beetleSW core/emulator producing with simular nice results.. 

Check **[THIS](https://forums.libretro.com/t/cg-shader-to-slang-vulkan-must-see-0-0/39930/12)** thread for more info about the .slangp variant shader in question and the results of it .




Bizhawk exception error code ↓
```
Pass 0:
Vertex Shader:

 System.InvalidOperationException: Error compiling shader: C:\Downloads\BizHawk_devbuild_aa0e2d6a\memory(169,14): error X3000: syntax error: unexpected token 'texture'
 ---> SlimDX.CompilationException: C:\Users\Michel\Downloads\BizHawk_devbuild_aa0e2d6a\memory(169,14): error X3000: syntax error: unexpected token 'texture'
 ---> SlimDX.Direct3D9.Direct3D9Exception: E_FAIL: An undetermined error occurred (-2147467259)

   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Object dataKey, Object dataValue)
   at SlimDX.CompilationException.Check[T](Int32 hr, String errors)

   --- End of inner exception stack trace ---

   at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
   at BizHawk.Bizware.DirectX.IGL_SlimDX9.CreateVertexShader(String source, String entry, Boolean required)
   --- End of inner exception stack trace ---
   at BizHawk.Bizware.DirectX.IGL_SlimDX9.CreateVertexShader(String source, String entry, Boolean required) 

-------

Fragment Shader:

System.InvalidOperationException: Error compiling shader: (169): error X3082: Object types are not allowed in structs
 ---> SlimDX.CompilationException: (169): error X3082: Object types are not allowed in structs
 ---> SlimDX.Direct3D9.Direct3D9Exception: E_FAIL: An undetermined error occurred (-2147467259)

   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Object dataKey, Object dataValue)
   at SlimDX.CompilationException.Check[T](Int32 hr, String errors)

   --- End of inner exception stack trace ---

   at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
   at BizHawk.Bizware.DirectX.IGL_SlimDX9.CreateFragmentShader(String source, String entry, Boolean required)

   --- End of inner exception stack trace ---
   at BizHawk.Bizware.DirectX.IGL_SlimDX9.CreateFragmentShader(String source, String entry, Boolean required) 
```

**Comment by CasualPokePlayer** [comment]
Does it work if you switch to OpenGL? (Config -> Display -> Display Method8

**Comment by metagondria** [comment]
> Does it work if you switch to OpenGL? (Config -> Display -> Display Method)

Hi,

No, same "exception" error pops up !

Software mode (GDI) , same thing ...!?

Cheers,
TD

**Comment by YoshiRulz** [comment]
> However, like have said previously... The shader does load / work, ONLY when rom is active and running

I missed this. And this is the first time you've said it, as far as I can see. Closing.
