### ISSUE TITLE
NRE from `IGL_SlimDX9.FreeRenderTarget`

### ISSUE THREAD

**Issue by metagondria** [TASEmulators/BizHawk#3496]
Hello,

Suddenly i get the following error !!  Haven't had this kind of this error before, wich is why is suspect either Gpu driver update or windows update or rare bug !! 

This ↓ the message i get !!

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.FreeRenderTarget(RenderTarget rt)
   at BizHawk.Client.EmuHawk.RenderTargetFrugalizer.Dispose()
   at BizHawk.Client.EmuHawk.DisplayManager.Dispose()
   at BizHawk.Client.EmuHawk.MainForm.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

cheers

**Comment by CasualPokePlayer** [comment]
How did this occur exactly? Was it just randomly? On opening BizHawk? Closing down BizHawk (the mainform is being disposed, which should indicate BizHawk was shutting down?)

**Comment by metagondria** [comment]
> When did this occur exactly? Was it just randomly? On opening BizHawk? Closing down BizHawk (the mainform is being disposed, which should indicate BizHawk was shutting down?)

This happened just now (today)!  It happends on all builds back to 2.3.x !?
Weird, the error only show up when using the shader i have posted in another thread..

Here's the thing, when i boot an game in bizhawk without any filtering and config my display settings while game is running, everything gets accepted and applied !?!  But not from an restart, then this message pops up !?

I COULD HAVE SWORN, that this shader used to run flawless in the past !!!!!  That's weird , to say the least !!
Iam willing to go as far as doing an fresh windows install... but.. i doubt that will fix it ...  

cheers,

**Comment by CasualPokePlayer** [comment]
What do you mean "from a restart."

When I said when, I meant when within your time of using BizHawk. As in when you started it up, when playing some rom / in the middle of use, or closing BizHawk.

**Comment by metagondria** [comment]
> What do you mean "from a restart."
> 
> When I said when, I meant when within your time of using BizHawk. As in if it was when you started it up, when playing some rom / in the middle of use, or closing BizHawk (to be clear the error indicates BizHawk was being closed somehow).

Like i said, right from the start, after i launch biz and boot an rom from an cold start *boom* i get that pesky message !?

Hence me saying, the shader only is fully applicable when an rom is currently running.  
Meaning, the game has to be booted first and during gameplay iam able to config display settings and load custom shader.
But this is the weird part, after i close down biz, and restart the emu load the rom boom i get that message again!  Most certainly to do with the shader in question, but it only shows that message when biz boots an game from the start !

Furthermore, i know for an fact its not an amd gpu driver conflict (reverted back to previous drivers), nor windows "security" update enterfeering !  Although , there's only so much you can revert regarding windows updates and what not unless you do an fresh install !  Some other upates are permanent regardless !


cheers,

**Comment by YoshiRulz** [comment]
This is the same stacktrace as #1610, but that was resolved by launching from a clean config, while this sounds like it's tied to the machine rather than a copy of BizHawk.

But, since the code in question was removed in https://github.com/TASEmulators/BizHawk/commit/8aac335d9b4e9748d9ed14c98b4bcb86a19e1129, I'm calling this resolved.
