### ISSUE TITLE
Lua `AccessViolationException` on `print({}, 1)`

### ISSUE THREAD

**Issue by kalimag** [TASEmulators/BizHawk#3513]
### Summary
Calling `print`, `console.log` or `console.writeline` when the first argument is a table followed by non-table arguments will crash BizHawk.

Setting breakpoints in `ConsoleLuaLibrary` and inspecting the `params object[] outputs` parameter shows that if the first argument is a table, all following arguments are supposedly of type `LuaTable` as well. So the bug appears to be somewhere in the code that binds Lua arguments to C#. It does not affect `joypad.set({}, 1)`, so the issue may be isolated to `params` arguments?

### Repro
Run following script:
```Lua
print({"ok"})
print({"ok"}, {"ok"})
print("ok", {"ok"})
print("ok", {"ok"}, "ok")

print({"crash"}, "crash")
print({"crash"}, 1, true, function() end)
```

### Output
On BizHawk 2.9:
```
System.AccessViolationException:
   at Bizhawk.BizInvokeProxyLua54NativeMethods.lua_next(IntPtr , Int32 )
   at NLua.Lua.GetTableDict(LuaTable table)
   at NLua.LuaTable.get_Keys()
   at BizHawk.Client.EmuHawk.ConsoleLuaLibrary.<LogWithSeparator>g__SerializeTable|12_0(LuaTable lti) in F:\Emulation\BizHawk\src\BizHawk.Client.EmuHawk\tools\Lua\Libraries\ConsoleLuaLibrary.cs:line 70
   at BizHawk.Client.EmuHawk.ConsoleLuaLibrary.<LogWithSeparator>g__SerializeAndWrite|12_1(Object output, <>c__DisplayClass12_0& ) in F:\Emulation\BizHawk\src\BizHawk.Client.EmuHawk\tools\Lua\Libraries\ConsoleLuaLibrary.cs:line 100
   at BizHawk.Client.EmuHawk.ConsoleLuaLibrary.LogWithSeparator(String separator, String terminator, Object[] outputs) in F:\Emulation\BizHawk\src\BizHawk.Client.EmuHawk\tools\Lua\Libraries\ConsoleLuaLibrary.cs:line 114
   at BizHawk.Client.EmuHawk.ConsoleLuaLibrary.Log(Object[] outputs) in F:\Emulation\BizHawk\src\BizHawk.Client.EmuHawk\tools\Lua\Libraries\ConsoleLuaLibrary.cs:line 48
   at BizHawk.Client.EmuHawk.LuaLibraries.Print(Object[] outputs) in F:\Emulation\BizHawk\src\BizHawk.Client.EmuHawk\tools\Lua\LuaLibraries.cs:line 348
```

### Host env.
- BizHawk 2.3 (oldest tested) up to 2.8 and 2.9 dev
- KeraLua and LuaInterface crash
- KopiLua does not crash, but prints `NLua.Exceptions.LuaScriptException: <last argument value>`, so probably corrupts the Lua stack in some way?

**Comment by YoshiRulz** [comment]
REPL behaviour for reference:
```
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
> print({"ok"})
table: 0x559ce8805b40
> print({"ok"}, {"ok"})
table: 0x559ce8806f40   table: 0x559ce88070b0
> print("ok", {"ok"})
ok      table: 0x559ce88073c0
> print("ok", {"ok"}, "ok")
ok      table: 0x559ce8807790   ok
> print({"crash"}, "crash")
table: 0x559ce8807b90   crash
> print({"crash"}, 1, true, function() end)
table: 0x559ce8808220   1       true    function: 0x559ce8807f00
```
