### ISSUE TITLE
mGBA system bus: I/O registers, VRAM, OAM, 

### ISSUE THREAD

**Issue by getCursorsExe** [TASEmulators/BizHawk#3537]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Whenever my cat sits on the left side of my keyboard, games run too fast for me to react to.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. first step
2. second step
3. et cetera

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.InvalidOperationException: o noes
  at BizHawk.Client.EmuHawk.HawkBiz.Crash()
  at BizHawk.Client.EmuHawk.HawkBiz.RunWithoutCrashing()
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.5.2; Win10 Pro 1903; AMD/AMD
- BizHawk 2.4.2; Win8.1; Intel/NVIDIA
- BizHawk dev build at 370996875; Win10 Home 1809; Intel/AMD
- BizHawk 2.5; Fedora 31; AMD/NVIDIA

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by YoshiRulz** [comment]
See also #3524 (you still haven't answered my question there, by the way).

I'm guessing this is unintentional; the system bus is [implemented separately](https://github.com/TASEmulators/mgba/blob/26ea5311797656a87ebfcabd55fe295a15e55535/src/platform/bizhawk/bizinterface.c#L595-L598) from [the other domains](https://github.com/TASEmulators/mgba/blob/26ea5311797656a87ebfcabd55fe295a15e55535/src/platform/bizhawk/bizinterface.c#L486-L507).

**Comment by CasualPokePlayer** [comment]
It's an "issue" upstream.
IO/PALRAM/VRAM/OAM are unimplemented
https://github.com/mgba-emu/mgba/blob/dbffb46c4e7d2e7a2cbed7c3488cece4c2176d4c/src/gba/memory.c#L1362-L1373
SRAM is partially implemented (only works when it's actually SRAM and not Flash/EEPROM/etc)
https://github.com/mgba-emu/mgba/blob/dbffb46c4e7d2e7a2cbed7c3488cece4c2176d4c/src/gba/memory.c#L1388-L1396

**Comment by getCursorsExe** [comment]
In VBA-Next, we could write to IO/PALRAM/VRAM/OAM as intended.

**Comment by getCursorsExe** [comment]
This would mean that debugging functions in mGBA core aren't even finished at all, but VBA-Next, it was.

**Comment by nattthebear** [comment]
Since `GBAPatch16` and `GBAPatch32` do implement those things, we could fix it in the memory domain by adding separate writeshort and writelong implementations.  This would probably be good enough, as in real usage you'd have little reason to write only 8 bits at a time to most of these locations.

**Comment by endrift** [comment]
Fixed in upstream bb8a6e05f9fb440efdf2121f08448814d6a7ed1f. No one ever told me this was a problem so I never knew.

**Comment by YoshiRulz** [comment]
Should be fixed?
