### ISSUE TITLE
Bizhawk 2.9 MAME nvram getting more than what is in the SaveRAM folder.

### ISSUE THREAD

**Issue by ASEPRL** [TASEmulators/BizHawk#3620]
Running "Raiden Fighters - Taiwan Single Board" bk2 playback files will get the wrong amount of NVRAM files.

Steps for repro :
1. Run romset RDFTS on bizhawk, creating a single nvram file.
2. playback previously recorded bk2 file from dev build (linked in issue)
3. error window mentions the nvram count is incorrect

Exception on drag and drop:
```
System.InvalidOperationException: Wrong NVRAM file count! (got 3, expected 1)
   at BizHawk.Emulation.Cores.Arcades.MAME.MAME.StoreSaveRam(Byte[] data)
   at BizHawk.Client.Common.MovieExtensions.ProcessSram(IMovie movie, IEmulator emulator)
   at BizHawk.Client.Common.MovieSession.RunQueuedMovie(Boolean recordMode, IEmulator emulator)
   at BizHawk.Client.EmuHawk.MainForm.StartNewMovie(IMovie movie, Boolean record)
   at BizHawk.Client.EmuHawk.MainForm.FormDragDrop_internal()
   at BizHawk.Client.EmuHawk.MainForm.<CheckMessages>b__226_0()
```

bk2 file
[funny.zip](https://github.com/TASEmulators/BizHawk/files/11186113/funny.zip)

**Comment by CasualPokePlayer** [comment]
The .SaveRAM format changed between dev versions, this is probably just breakage between versions.
