### ISSUE TITLE
C64 disc (tape) switching leads to NRE

### ISSUE THREAD

**Issue by YoshiRulz** [TASEmulators/BizHawk#3683]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Emulation.Cores.Computers.Commodore64.C64.SetDisk(Int32 discNum)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Lead suspect:
https://github.com/TASEmulators/BizHawk/blob/4ee7e4cad7129d4e8b2ef7817079ae2c1b99052c/src/BizHawk.Emulation.Cores/Computers/Commodore64/C64.cs#L213

Initially reported by jmwtac on Discord.

**Comment by SaxxonPike** [comment]
While I'm working on C64 stuff I will re-check this one after the recent disk changes.

**Comment by SaxxonPike** [comment]
We need this revisited in the latest release - there have been substantial changes to state sync in the C64 disk emulation.
