### ISSUE TITLE
Exception when Arcade movie recording -- Bizhawk (dev build) crashes when trying to record some games that have duplicate / mirrored controls.

### ISSUE THREAD

**Issue by Mad-Matty** [TASEmulators/BizHawk#3704]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary

An Exception is raised when attempting to record a movie when recording a game with duplicate / mirrored controls.

Example game is STUN Runner (rev 6) (stunrun.zip) from latest 0/256 romset (can be merged or split). The same issue can be observed with Outrunners (orunners.zip)

These games have multiple coin and start buttons. Setting one is mirrored to the other.  In the case of stun runner it is Coin 1 causing a problem.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."

Bizhawk 2.9.2 Dev up to commit 9daac2c is the last working version.
 
Bizhawk 2.9.2 Dev commit 05f8747 introduces the issue.

1. Load stunrun.zip (opens in mamehawk)
2. Record movie
3. An exception will occur.

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at BizHawk.Client.Common.Bk2LogEntryGenerator..ctor(String systemId, IController source)
   at BizHawk.Client.Common.Bk2Movie.LogGeneratorInstance(IController source)
   at BizHawk.Client.Common.Bk2Movie.RecordFrame(Int32 frame, IController source)
   at BizHawk.Client.Common.MovieSession.HandleFrameBefore()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
BizHawk 2.9.2 Dev build (05f8747) ; Win11 Pro 2h22; AMD/AMD

Latest .Net and VS2022 fully updated

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by kalimag** [comment]
Before 05f874732195622824ab964f90315f6532d300d0 starting a movie recording from the menu doesn't throw an exception on duplicate control names, but opening TAStudio causes a similar exception even before that commit (on 9daac2c26f9bc6315b3773a2b5b6f19da3db8309 and 2.9.1 release):

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at BizHawk.Client.Common.Bk2LogEntryGenerator.Map() in F:\Emulation\BizHawk\src\BizHawk.Client.Common\movie\bk2\Bk2LogEntryGenerator.cs:Line 50.
   at BizHawk.Client.EmuHawk.TAStudio.SetUpColumns()
   at BizHawk.Client.EmuHawk.TAStudio.StartNewTasMovie()
   at BizHawk.Client.EmuHawk.TAStudio.Engage()
   at BizHawk.Client.EmuHawk.TAStudio.Tastudio_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at BizHawk.Client.EmuHawk.FormBase.OnLoad(EventArgs e)
```

**Comment by vadosnaprimer** [comment]
Do the duplicate buttons do anything different in actual MAME for this game?

**Comment by Mad-Matty** [comment]
By default, the two coin options are on the same key.  I moved the main coin buttons up to 8 and 9.  The game responds to 8 and 9 but not the other coin buttons on 5,6,7

In Bizhawk, Setting a button to the two main coin buttons will not save anything, and will remain as previous state.  Changing the lower three coins will mirror the button to the top two main coins.

![mamestunrun](https://github.com/TASEmulators/BizHawk/assets/13140873/7e188b45-6820-4c2a-8cac-b442f63cc914)

**Comment by infinitephantasm** [comment]
i still seem to be encountering this on the latest interim build, specifically when running/using beatmania 3rdMIX (bm3rdmix.zip)

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at BizHawk.Client.Common.Bk2LogEntryGenerator..ctor(String systemId, IController source)
   at BizHawk.Client.Common.Bk2Movie.LogGeneratorInstance(IController source)
   at BizHawk.Client.Common.Bk2Movie.WriteInputLog(TextWriter writer)
   at BizHawk.Client.Common.ZipStateSaver.<>c__DisplayClass7_0.<PutLump>b__0(Stream s)
   at BizHawk.Client.Common.FrameworkZipWriter.WriteItem(String name, Action`1 callback, Boolean zstdCompress)
   at BizHawk.Client.Common.ZipStateSaver.PutLump(BinaryStateLump lump, Action`1 callback)
   at BizHawk.Client.Common.Bk2Movie.AddBk2Lumps(ZipStateSaver bs)
   at BizHawk.Client.Common.Bk2Movie.Write(String fn, Boolean isBackup)
   at BizHawk.Client.EmuHawk.RecordMovie.Ok_Click(Object sender, EventArgs e)
```

error appears when trying to record a movie or opening TAStudio

**Comment by YoshiRulz** [comment]
^ Try that dev build when the CI job finishes

**Comment by infinitephantasm** [comment]
updated error:

```
System.ArgumentException: duplicate KEY Reset in input log mnemonic cache (was r, attempting to set r)
Parameter name: source ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at BizHawk.Client.Common.Bk2LogEntryGenerator..ctor(String systemId, IController source) in /src/BizHawk.Client.Common/movie/bk2/Bk2LogEntryGenerator.cs:line 29
   --- End of inner exception stack trace ---
   at BizHawk.Client.Common.Bk2LogEntryGenerator..ctor(String systemId, IController source) in /src/BizHawk.Client.Common/movie/bk2/Bk2LogEntryGenerator.cs:line 33
   at BizHawk.Client.Common.Bk2Movie.LogGeneratorInstance(IController source) in /src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs:line 40
   at BizHawk.Client.Common.Bk2Movie.RecordFrame(Int32 frame, IController source) in /src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs:line 70
   at BizHawk.Client.Common.MovieSession.HandleFrameBefore() in /src/BizHawk.Client.Common/movie/MovieSession.cs:line 96
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force) in /src/BizHawk.Client.EmuHawk/MainForm.cs:line 3196
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in /src/BizHawk.Client.EmuHawk/MainForm.cs:line 837
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in /src/BizHawk.Client.EmuHawk/Program.cs:line 349
```

**Comment by vadosnaprimer** [comment]
Maybe it's because I add soft reset to every machine, and this one already has its own.

**Comment by infinitephantasm** [comment]
apologies for the late response, but that commit seems to have resolved the issue! thank you!
