### ISSUE TITLE
Unable to convert .gmv to .bk2 - Null Core

### ISSUE THREAD

**Issue by Meerkov** [TASEmulators/BizHawk#3797]
Tested in 2.9.1 and 2.8

1) Load El Viento
2) Try converting the .gmv from tasvideos to .bk2 using the "Import" menu.
3) Try loading the movie (various ways, drag an drop, open in TAStudio, etc)
4) Warning about a null core, then a null reference exception is thrown and it gives up.

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.MovieConversionExtensions.ToTasMovie(IMovie old)
   at BizHawk.Client.Common.MovieSession.ConvertToTasProj()
   at BizHawk.Client.EmuHawk.TAStudio.ConvertCurrentMovieToTasproj()
   at BizHawk.Client.EmuHawk.TAStudio.LoadMovieFile(String filename, Boolean askToSave)
   at BizHawk.Client.EmuHawk.TAStudio.OpenTasMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Meerkov** [comment]
For whatever reason, this *does* work
1) load El Viento
2) Drag and drop the .gmv movie into 2.9.1
3) Then open TasStudio

This doesn't throw an exception, but trying to convert from .gmv to .bk2 first does.

**Comment by YoshiRulz** [comment]
CNR on 2.9.1 or master at ac3913ded. Rom hash is `SHA1:B53E9017...` and I presume you were using [this movie](https://tasvideos.org/977M).

**Comment by Meerkov** [comment]
[Socket (U) [!].zip](https://github.com/TASEmulators/BizHawk/files/13161435/Socket.U.zip)
Here's another old Genesis movie that I can't seem to get converted.

**Comment by Meerkov** [comment]
![image](https://github.com/TASEmulators/BizHawk/assets/8139496/ac718923-b957-4178-a4f4-6037aae7fc15)
Trying to open in TasStudio throws this error forever until you force quit

**Comment by Meerkov** [comment]
I was able to eventually get it working by manually fixing the Input Log file, as the conversion only converted controller 2 to a 6 button input, but not controller 1. And as a result the input file was totally messed up.

**Comment by Morilli** [comment]
Can also not reproduce.

**Comment by YoshiRulz** [comment]
The *Socket* sample failed for me.

**Comment by Morilli** [comment]
Okay that's apparently due to the importer (correctly) importing the first controller as 3-button controller and the second as 6-button, which is not supported by the sync setting that toggles 3/6 for both controllers.
