### ISSUE TITLE
DSiware games do not works

### ISSUE THREAD

**Issue by ozderya** [TASEmulators/BizHawk#3840]
[//]: # "This description supports Markdown syntax. There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "These lines are comments, for letting you know what you should be writing. You can delete them or leave them in."
[//]: # "Also, please don't waste your time writing until you've checked for similar Issues. Remember to check closed Issues too!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
All games listed below are DSiWare games. While DS Tangrams is working great, DSiWare version listed blelow is not working. 

NDS load error
A core accepted the rom, but threw an exception while loading it:
- [x] California Super Sports (USA) --(Fixed with 7ceb634 )
- [ ] Cake Ninja Xmas (USA) (Es) --(Cannot find TMD for title ID 000300044b594e45)
- [ ] Mysterious Stars - A Fairy Tale (USA) --(Cannot find TMD for title ID 000300044b593645)
- [ ] Mysterious Stars - The Samurai (USA) --(Cannot find TMD for title ID 000300044b593745)
- [ ] Tangrams (USA) --(Cannot find TMD for title ID 000300044b595945)

White Screen
- [ ] Looksley's Line Up (USA)

There might be more games like above so when I find more games I will extend the list.
If anyone finds more games like above, feel free to edit this report.
### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1- Open the game

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
---------------------------
NDS load error
---------------------------
A core accepted the rom, but threw an exception while loading it:

System.Exception: Cannot find TMD for title ID 000300044b594e45, please report

   at BizHawk.Emulation.Cores.Consoles.Nintendo.NDS.NDS.GetTMDData(UInt64 titleId)

   at BizHawk.Emulation.Cores.Consoles.Nintendo.NDS.NDS..ctor(CoreLoadParameters`2 lp)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at BizHawk.Emulation.Cores.CoreInventory.Core.Create(ICoreInventoryParameters cip)

   at BizHawk.Client.Common.RomLoader.MakeCoreFromCoreInventory(CoreInventoryParameters cip, String forcedCoreName)
---------------------------
OK   
---------------------------

```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"

- BizHawk 2.9.2 - dev build 8be0111 ; Windows 11 Pro

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by CasualPokePlayer** [comment]
> Goony (USA)

Not sure when this got "fixed", but it seems to work fine now (albeit it runs at 2 FPS, log window indicates it uses the DSP, which is an absolute performance killer)

> Looksley's Line Up (USA)

Seems to "whitescreen" too, although it also ends up running very slowly and it seems to be another DSP game (might also actually be working and it just takes a long while to load up?)

**Comment by CasualPokePlayer** [comment]
DSP games should function at full speed since last upstream pull.
