### ISSUE TITLE
[TAStudio] Custom Columns Broken Since Release 2.9

### ISSUE THREAD

**Issue by Isotarge** [TASEmulators/BizHawk#3897]
### Summary
TAStudio custom columns appear to be broken shortly after BizHawk 2.8.
I have tested this with my own game and Lua script: Knight Shift and ScriptHawk.
When running those two together with TAStudio open, I get an exception, a red X where the list view for inputs should be, and the custom columns are not displayed.

I am using the following functions in the TAStudio Lua module:
- tastudio.engaged()
- tastudio.addcolumn()
- tastudio.onqueryitemtext()
- tastudio.onqueryitembg()
- tastudio.setlag()

### Repro
1. Open Knight Shift (Demo Version 1).sms from https://integer-max.itch.io/knight-shift
2. Open TAStudio
3. Open Lua Console and ScriptHawk (TAS Safe).lua from https://github.com/Isotarge/ScriptHawk/commit/cd3075f9162bb3211f1d9aec4d306c985567d0ce (requires a full clone of the ScriptHawk repo, it's not a standalone script)
4. Unpause the emulator

### Output
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BizHawk.Client.EmuHawk.TAStudioLuaLibrary.<>c__DisplayClass40_0.<OnQueryItemText>b__0(Int32 index, String name) in /_/src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/TAStudioLuaLibrary.cs:line 516
   at BizHawk.Client.EmuHawk.TAStudio.TasView_QueryItemText(Int32 index, RollColumn column, String& text, Int32& offsetX, Int32& offsetY) in /_/src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs:line 310
   at BizHawk.Client.EmuHawk.InputRoll.DrawData(List`1 visibleColumns, Int32 firstVisibleRow, Int32 lastVisibleRow) in /_/src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.Drawing.cs:line 312
   at BizHawk.Client.EmuHawk.InputRoll.OnPaint(PaintEventArgs e) in /_/src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.Drawing.cs:line 60
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Host env.
- BizHawk 2.9.1; Win10 Pro 22H2; AMD/NVIDIA
- BizHawk dev build at d415bf4c; Win10 Pro 22H2; AMD/NVIDIA

BizHawk 2.8 or earlier (working) (tested back to 2.2.2)

![image](https://github.com/TASEmulators/BizHawk/assets/6367891/2bbaf0d8-a045-4458-9438-d579d84d11ea)

BizHawk 2.9 or later (broken)

![image](https://github.com/TASEmulators/BizHawk/assets/6367891/8c395612-4645-4669-966d-30be50a6c807)

**Comment by YoshiRulz** [comment]
The only way
https://github.com/TASEmulators/BizHawk/blob/45e2307a7bfd087d3dac38f886b1af349953e7a9/src/BizHawk.Client.EmuHawk/tools/Lua/Libraries/TAStudioLuaLibrary.cs#L510-L520
could give an IooRE would be if the callback is returning 0 values. Add a `return nil;` [here](https://github.com/Isotarge/ScriptHawk/blob/cd3075f9162bb3211f1d9aec4d306c985567d0ce/ScriptHawk.lua#L1254-L1255).

I'm guessing the implementation of `Call` in the old Lua engines was `null` (or maybe `new object?[] { null }`) for empty `return`s, while the new engine has `new object?[] {}`. (I don't believe the Lua language makes that distinction.)

**Comment by Isotarge** [comment]
Okie dokie, thank you for the fast response :)
