### ISSUE TITLE
There was an error importing the bkm Movie program

### ISSUE THREAD

**Issue by sakurayz** [TASEmulators/BizHawk#3909]
EmuHawk Ver: 2.9.2 dev build
Windows 10 Version 10.0.19044

Unhandled exception has occurred in a component in your
application. Ifyou click Continue. the application will ignore
this error and atemptto continue.
Object reference not set to an instance of an object

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.movie.import.BkmImport.RunImport()
   at BizHawk.Client.Common.MovieImporter.Import(IDialogParent dialogParent, IMovieSession session, String path, Config config)
   at BizHawk.Client.Common.MovieImport.ImportFile(IDialogParent dialogParent, IMovieSession session, String path, Config config)
   at BizHawk.Client.EmuHawk.MainForm.ProcessMovieImport(String fn, Boolean start)
   at BizHawk.Client.EmuHawk.MainForm.ImportMovieMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by YoshiRulz** [comment]
Can you copy the commit hash from `Help` > `About...`? And are you able to share the movie or link to where you found it?

**Comment by Morilli** [comment]
Yeah bkm importing is completely broken currently...
