### ISSUE TITLE
Can't launch 2 iQue DSiWare Titles due to missing TMD

### ISSUE THREAD

**Issue by Tailx501** [TASEmulators/BizHawk#4028]
### Summary
When I tried to launch 2 iQue DSiWare Titles with the iQue Firmware and BIOS set up, it throws me an error stating that a TMD for these 2 Titles are missing.

* Niǎo hé Dòu (iQue) [TWL-KP6C-CHN] --(Cannot find TMD for title ID 000300044b503643)
* Zhǐ Fēijī Tiǎozhàn (iQue) [TWL-KAMC-CHN] --(Cannot find TMD for title ID 000300044b414d43)

### Repro
1. Open the game.
2. Error

### Output
```
---------------------------
NDS load error
---------------------------
A core accepted the rom, but threw an exception while loading it:

System.Exception: Cannot find TMD for title ID 000300044b503643, please report

   at BizHawk.Emulation.Cores.Consoles.Nintendo.NDS.NDS.GetTMDData(UInt64 titleId)

   at BizHawk.Emulation.Cores.Consoles.Nintendo.NDS.NDS..ctor(CoreLoadParameters`2 lp)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at BizHawk.Emulation.Cores.CoreInventory.Core.Create(ICoreInventoryParameters cip)

   at BizHawk.Client.Common.RomLoader.MakeCoreFromCoreInventory(CoreInventoryParameters cip, String forcedCoreName)
---------------------------
OK   
---------------------------


---------------------------
NDS load error
---------------------------
A core accepted the rom, but threw an exception while loading it:

System.Exception: Cannot find TMD for title ID 000300044b414d43, please report

   at BizHawk.Emulation.Cores.Consoles.Nintendo.NDS.NDS.GetTMDData(UInt64 titleId)

   at BizHawk.Emulation.Cores.Consoles.Nintendo.NDS.NDS..ctor(CoreLoadParameters`2 lp)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at BizHawk.Emulation.Cores.CoreInventory.Core.Create(ICoreInventoryParameters cip)

   at BizHawk.Client.Common.RomLoader.MakeCoreFromCoreInventory(CoreInventoryParameters cip, String forcedCoreName)
---------------------------
OK   
---------------------------
```

### Host env.
- BizHawk [2.9.1](https://github.com/TASEmulators/BizHawk/releases/tag/2.9.1); Windows 11; INTEL/NVIDIA

**Comment by Tailx501** [comment]
And even using the latest development build still get me the same missing TMD error.

**Comment by CasualPokePlayer** [comment]
Upstream downloads TMDs from Nintendo's servers, so they should work assuming Nintendo's servers still has them. BizHawk rather just bundles all the TMDs in BizHawk (although some TMDs are missing).
