### ISSUE TITLE
Emulating a frame of a GB game crashes

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#4057]
Looks probable the recent Axis changes had an oversight.

It happened with the Game Boy games I tested, but didn't affect an SNES game or GBA game I tested. Emulating in TAStudio with recording mode off works fine.

I noticed this while trying to test an unrelated issue.

### Output
```
System.Collections.Generic.KeyNotFoundException: The given key 'Remote Command' was not present in the dictionary.
   at System.Collections.Immutable.ImmutableDictionary`2.get_Item(TKey key)
   at BizHawk.Client.Common.ORAdapter.AxisValue(String name) in /src/BizHawk.Client.Common/inputAdapters/BitwiseAdapters.cs:line 84
   at BizHawk.Client.Common.XorAdapter.AxisValue(String name) in /src/BizHawk.Client.Common/inputAdapters/BitwiseAdapters.cs:line 52
   at BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy.FrameAdvancePrep(IController controller) in /src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.cs:line 453
   at BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy.FrameAdvance(IController controller, Boolean render, Boolean rendersound) in /src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.IEmulator.cs:line 18
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force) in /src/BizHawk.Client.EmuHawk/MainForm.cs:line 3042
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in /src/BizHawk.Client.EmuHawk/MainForm.cs:line 894
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in /src/BizHawk.Client.EmuHawk/Program.cs:line 346
```

### Host env.
- BizHawk 2.10 dev build at 15ff0ec2c703d5f21ae963e2b580a7d7048ff5b3; Win11

**Comment by YoshiRulz** [comment]
As with #4056, this is likely a bug in the core which has been silently failing for a long time.

**Comment by CasualPokePlayer** [comment]
"Remote Command" is an axis input update per frame, although such an update does absolutely nothing if the remote control isn't enabled in the sync setting (remote control input callback would not be set).
