### ISSUE TITLE
Greenzone is unstable recently

### ISSUE THREAD

**Issue by RetroEdit** [TASEmulators/BizHawk#4074]
In the latest dev build ( d513632cf96fe6ff98d7c36a776a6c4969963b35 ), I'm having a lot of weird behavior with greenzone in TAStudio.

For one, even after running `Clear greenzone`, TAStudio still allowed seeking to previous greenzone frames. Same with pressing and then unpressing an input on frame 0 (which should generally be basically equivalent to clear greenzone).

I also got this exception a few times while re-recording over a section and was able to consistently reproduce it:
```
System.InvalidOperationException: Savestate buffer size mismatch!
   at BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy.LoadStateBinary(BinaryReader reader) in /src/BizHawk.Emulation.Cores/Consoles/Nintendo/Gameboy/Gambatte.IStatable.cs:line 74
   at BizHawk.Client.EmuHawk.TAStudio.LoadState(KeyValuePair`2 state, Boolean discardApiHawkSurfaces) in /src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs:line 903
   at BizHawk.Client.EmuHawk.TAStudio.StartAtNearestFrameAndEmulate(Int32 frame, Boolean fromLua, Boolean fromRewinding) in /src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs:line 853
   at BizHawk.Client.EmuHawk.TAStudio.GoToFrame(Int32 frame, Boolean fromLua, Boolean fromRewinding, Boolean OnLeftMouseDown) in /src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.Navigation.cs:line 42
   at BizHawk.Client.EmuHawk.TAStudio.TasView_MouseDown(Object sender, MouseEventArgs e) in /src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.ListView.cs:line 581
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at BizHawk.Client.EmuHawk.InputRoll.OnMouseDown(MouseEventArgs e) in /src/BizHawk.Client.EmuHawk/CustomControls/InputRoll/InputRoll.cs:line 1242
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I also got this message when opening a `.tasproj`: `State history was corrupted, clearing and working with a fresh history.`

"Clear greenzone" not working seems very reproducible, I just opened TAStudio from a fresh config and emulated around 10000 frames and then attempted to clear greenzone.

A quick bisect says the culprit seems to be 2d229be6ba26d3c30c9e055ba89a1d67e5e7b010

**Comment by Morilli** [comment]
Please re-test to confirm f28fa497955e332dca0fdae57c08c98ed10b01b3 fixes all of those issues, but I'm positive it should.

I was testing with the quickernes core, which does not show any problems until frame >16383, so I didn't notice this.
